import tensorflow as tf
import os,sys
from sklearn.preprocessing import StandardScaler
import pandas as pd


def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)

version = 4

X_train = pd.read_csv(resource_path(f'X_train_load{version}.csv'),index_col=False)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)


saved_model = tf.keras.models.load_model(resource_path(f"TF_model_prototipe{version}"))




VELOCIDAD = 239
HARDENING_TEMP = 944.9
HARDENING_VOLT = 544
TEMPERING_TEMP = 470
TEMPERING_VOLT = 196
HARDENING_AMP = 529
HARDENING_FREQ = 311
HARDENING_POW = 232
Quenching_Temp = 860.9
line = 1
HARDENING_FLUJO_1 = 2129
HARDENING_FLUJO_2 = 2303
HARDENING_FLUJO_3 = 702
HARDENING_FLUJO_4 = 1122
HARDENING_FLUJO_5 = 1188
TEMPERING_FLUJO_1 = 1218
TEMPERING_FLUJO_2 = 1128
TEMPERING_FLUJO_3 = 1020
TEMPERING_FLUJO_4 = 690
TEMP_AGUA_HARDENING = 31.5
TEMP_AGUA_TEMPERING = 31.5
Diam = 14.10

#valor 1971

scaled = scaler.transform([[VELOCIDAD,HARDENING_TEMP,HARDENING_VOLT,TEMPERING_TEMP,TEMPERING_VOLT,HARDENING_FLUJO_1,HARDENING_FLUJO_2,HARDENING_FLUJO_3,HARDENING_FLUJO_4,HARDENING_FLUJO_5,TEMPERING_FLUJO_1,TEMPERING_FLUJO_2,TEMPERING_FLUJO_3,TEMPERING_FLUJO_4,TEMP_AGUA_HARDENING,TEMP_AGUA_TEMPERING,HARDENING_AMP,HARDENING_FREQ,HARDENING_POW,Quenching_Temp,line,Diam]])
#scaled = scaler.transform([[VELOCIDAD,HARDENING_VOLT,TEMPERING_VOLT,TEMP_AGUA_HARDENING,TEMP_AGUA_TEMPERING,HARDENING_AMP,HARDENING_FREQ,HARDENING_POW,Quenching_Temp,line,Diam]])

print(saved_model.predict(scaled))


VELOCIDAD = 229
HARDENING_TEMP = 949
HARDENING_VOLT = 510
TEMPERING_TEMP = 496.39
TEMPERING_VOLT = 203
HARDENING_AMP = 189
HARDENING_FREQ = 318
HARDENING_POW = 189
Quenching_Temp = 853.90
line = 3
HARDENING_FLUJO_1 = 2021
HARDENING_FLUJO_2 = 2195
HARDENING_FLUJO_3 = 984
HARDENING_FLUJO_4 = 1440
HARDENING_FLUJO_5 = 1476
TEMPERING_FLUJO_1 = 1110
TEMPERING_FLUJO_2 = 1488
TEMPERING_FLUJO_3 = 1182
TEMPERING_FLUJO_4 = 942
TEMP_AGUA_HARDENING = 30.10
TEMP_AGUA_TEMPERING = 30
Diam = 13.10

#valor 1997

scaled = scaler.transform([[VELOCIDAD,HARDENING_TEMP,HARDENING_VOLT,TEMPERING_TEMP,TEMPERING_VOLT,HARDENING_FLUJO_1,HARDENING_FLUJO_2,HARDENING_FLUJO_3,HARDENING_FLUJO_4,HARDENING_FLUJO_5,TEMPERING_FLUJO_1,TEMPERING_FLUJO_2,TEMPERING_FLUJO_3,TEMPERING_FLUJO_4,TEMP_AGUA_HARDENING,TEMP_AGUA_TEMPERING,HARDENING_AMP,HARDENING_FREQ,HARDENING_POW,Quenching_Temp,line,Diam]])
#scaled = scaler.transform([[VELOCIDAD,HARDENING_VOLT,TEMPERING_VOLT,TEMP_AGUA_HARDENING,TEMP_AGUA_TEMPERING,HARDENING_AMP,HARDENING_FREQ,HARDENING_POW,Quenching_Temp,line,Diam]])
print(saved_model.predict(scaled))


VELOCIDAD = 245
HARDENING_TEMP = 925.7
HARDENING_VOLT = 575
TEMPERING_TEMP = 488.2
TEMPERING_VOLT = 195
HARDENING_AMP = 305
HARDENING_FREQ = 296
HARDENING_POW = 120
Quenching_Temp = 886.59
line = 1
HARDENING_FLUJO_1 = 2651
HARDENING_FLUJO_2 = 2237
HARDENING_FLUJO_3 = 780
HARDENING_FLUJO_4 = 1458
HARDENING_FLUJO_5 = 1140
TEMPERING_FLUJO_1 = 1356
TEMPERING_FLUJO_2 = 1248
TEMPERING_FLUJO_3 = 1212
TEMPERING_FLUJO_4 = 858
TEMP_AGUA_HARDENING = 26.39
TEMP_AGUA_TEMPERING = 26.29
Diam = 13.80

#valor 1999

scaled = scaler.transform([[VELOCIDAD,HARDENING_TEMP,HARDENING_VOLT,TEMPERING_TEMP,TEMPERING_VOLT,HARDENING_FLUJO_1,HARDENING_FLUJO_2,HARDENING_FLUJO_3,HARDENING_FLUJO_4,HARDENING_FLUJO_5,TEMPERING_FLUJO_1,TEMPERING_FLUJO_2,TEMPERING_FLUJO_3,TEMPERING_FLUJO_4,TEMP_AGUA_HARDENING,TEMP_AGUA_TEMPERING,HARDENING_AMP,HARDENING_FREQ,HARDENING_POW,Quenching_Temp,line,Diam]])
#scaled = scaler.transform([[VELOCIDAD,HARDENING_VOLT,TEMPERING_VOLT,TEMP_AGUA_HARDENING,TEMP_AGUA_TEMPERING,HARDENING_AMP,HARDENING_FREQ,HARDENING_POW,Quenching_Temp,line,Diam]])
print(saved_model.predict(scaled))